//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class CSVStrings
{
	public static readonly string Wall = "wall";
	public static readonly string Empty = "empty";
	public static readonly string TeamMember = "tm";
	public static readonly string ProjectOwner = "po";
	public static readonly string ScrumMaster = "sm";


	private CSVStrings ()
	{
	}
}

