//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Levels
{
	private static TextAsset testLevel; 
	public static TextAsset TestLevel
	{
		get
		{
			if(testLevel == null){
				testLevel = Resources.Load("Levels/TestLevel") as TextAsset;
			}
			return testLevel;
		}
	}
}

