//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class PrefabStrings
{
	public static readonly string Wall = "Prefabs/"+ "Wall";
	public static readonly string GridTile = "Prefabs/" + "GridTile";
	public static readonly string ProjectOwner = "Prefabs/" + "GridTile";
	public static readonly string TeamMember = "Prefabs/" + "TeamMember";
	public static readonly string ScrumMaster = "Prefabs/" + "ScrumMaster";

	private PrefabStrings ()
	{
	}

}
