//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class TeamMember : Person
{
	public enum State {Idle, Moving, Working, Eating, Talking};

	public int TeamMemberNumber;
	public State CurrentState;

	void Start () {
	}
	
	// Update is called once per frame
	void Update () {
		switch (CurrentState) {
		case State.Moving:
			moveRight();
			break;
		case State.Talking:
			moveOtherPersonRightByTag("TeamMember2");
			break;
		}
	}
}
